[package]
name = "screento"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fontster = { git = "https://github.com/gennyble/fontster" }
gifed = { path = "../gifed/gifed" }